version: '3.8'

services:

  frontend:
    build:
      context: ./auth-interface
    ports:
      - "4200:8585"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - d0ck3r-network
    depends_on:
      - backend

  backend:
    build:
      context: ./auth-api
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    ports:
      - 3000
    networks:
      - d0ck3r-network

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: docker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - d0ck3r-network
    ports:
      - 5432

networks:
  d0ck3r-network:

