

services:


  frontend:
    build:
      context: ./auth-interface
    ports:
      - 443:443
      - 81:80
    # volumes:
      # - ./frontend:/usr/src/app
      # - /usr/src/app/node_modules
    restart: always
    networks:
      - d0ck3r-network
    depends_on:
      - backend


  backend:
    build:
      context: ./auth-api
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    networks:
      - d0ck3r-network
    # ports:
    #   - 3000:3000


  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: docker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - d0ck3r-network


networks:
  d0ck3r-network:
    driver: bridge
